- name: Create Istio install dir
  file:
    path: "{{ istio_dir }}"
    state: directory

- name: Install Istio
  unarchive:
    src: "{{ istio_package_url }}"
    dest: "{{ istio_dir }}"
    remote_src: yes
