- name: Check Istio installed
  stat:
    path: "{{ istio_bin }}"
  register: _istio_bin

- name: Handle Istio install
  include_tasks:
    file: apply.yml
  when:
    - not _istio_bin.stat.exists

- name: Check Istio installed on kubernetes
  shell:
    kubectl get -n istio-system service/istiod -o jsonpath='{.metadata.labels.operator\.istio\.io\/version}'
  register: _istio_version_deployed
  failed_when:
    - _istio_version_deployed.rc != 0 and not "NotFound" in _istio_version_deployed.stderr

- name: Handle Istio deploy
  include_tasks:
    file: deploy.yml
  when:
    - _istio_bin.stat.exists and "NotFound" in _istio_version_deployed.stderr

- name: Check Istio installed on kubernetes
  shell:
    kubectl get -n istio-system service/istiod -o jsonpath='{.metadata.labels.operator\.istio\.io\/version}'
  register: _istio_version_deployed
  failed_when:
    - _istio_version_deployed.rc != 0 and not "NotFound" in _istio_version_deployed.stderr

- name: Check grafana installed
  shell:
    kubectl get -n istio-system service/grafana -o jsonpath='{.metadata.labels.app\.kubernetes\.io\/version}'
  register: _istio_grafana_deployed
  failed_when:
    - _istio_grafana_deployed.rc != 0 and not "NotFound" in _istio_grafana_deployed.stderr

- name: Handle Istio plugins
  include_tasks:
    file: plugins.yml
  when:
    - _istio_bin.stat.exists and "NotFound" in _istio_grafana_deployed.stderr
