k8s_common_add_packages_keys:
  - key: https://download.docker.com/linux/debian/gpg
  - key: https://packages.cloud.google.com/apt/doc/apt-key.gpg


k8s_common_add_packages_repositories:
  - repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ansible_distribution_release}} stable"
  - repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"

k8s_common_add_packages_names:
  - name: curl
  - name: containerd.io
  - name: kubeadm
  - name: kubelet
  - name: kubectl

k8s_common_modprobe:
  - name: overlay
  - name: br_netfilter

k8s_common_sysctl:
  - name: net.bridge.bridge-nf-call-iptables
    value: 1
  - name: net.ipv4.ip_forward
    value: 1
  - name: net.bridge.bridge-nf-call-ip6tables
    value: 1

k8s_common_admin_user: "debian"
k8s_common_admin_group: "debian"