- name: Create carts deployment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Deployment
      metadata:
        name: carts
        labels:
          app: carts
          version: v1
        namespace: sock-shop
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: carts
            version: v1
        template:
          metadata:
            labels:
              app: carts
              version: v1
          spec:
            terminationGracePeriodSeconds: 5
            containers:
              - name: carts
                image: weaveworksdemos/carts:0.4.8
                env:
                  - name: JAVA_OPTS
                    value: -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
                resources:
                  limits:
                    cpu: 300m
                    memory: 500Mi
                  requests:
                    cpu: 100m
                    memory: 200Mi
                livenessProbe:
                  httpGet:
                    path: /health
                    port: 80
                  initialDelaySeconds: 300
                  periodSeconds: 3
                readinessProbe:
                  httpGet:
                    path: /health
                    port: 80
                  initialDelaySeconds: 180
                  periodSeconds: 3
                ports:
                  - containerPort: 80
                securityContext:
                  runAsNonRoot: true
                  runAsUser: 10001
                  capabilities:
                    drop:
                      - all
                    add:
                      - NET_BIND_SERVICE
                  readOnlyRootFilesystem: true
                volumeMounts:
                  - mountPath: /tmp
                    name: tmp-volume
            volumes:
              - name: tmp-volume
                emptyDir:
                  medium: Memory
            nodeSelector:
              beta.kubernetes.io/os: linux

- name: Create carts service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: carts
        annotations:
          prometheus.io/scrape: 'true'
        labels:
          name: carts
        namespace: sock-shop
      spec:
        type: ClusterIP
        ports:
          - name: http
            port: 80
            targetPort: 80
        selector:
          app: carts
