- name: Create carts db deployment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: carts-db
        labels:
          app: carts-db
          version: v1
        namespace: sock-shop
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: carts-db
            version: v1
        template:
          metadata:
            labels:
              app: carts-db
              version: v1
          spec:
            containers:
              - name: carts-db
                image: mongo
                ports:
                  - name: mongo
                    containerPort: 27017
                securityContext:
                  capabilities:
                    drop:
                      - all
                    add:
                      - CHOWN
                      - SETGID
                      - SETUID
                  readOnlyRootFilesystem: true
                volumeMounts:
                  - mountPath: /tmp
                    name: tmp-volume
                livenessProbe:
                  exec:
                    command:
                      - /bin/sh
                      - -c
                      - mongo --port 27018 --eval "rs.status()" | grep -vq "REMOVED"
                  initialDelaySeconds: 45
                  timeoutSeconds: 5
            volumes:
              - name: tmp-volume
                emptyDir:
                  medium: Memory
            nodeSelector:
              beta.kubernetes.io/os: linux

- name: Create carts db service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: carts-db
        namespace: sock-shop
      spec:
        type: ClusterIP
        ports:
          - name: tcp
            port: 27017
            targetPort: 27017
        selector:
          app: carts-db
