- name: Create catalogue deployment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Deployment
      metadata:
        name: catalogue
        labels:
          app: catalogue
          version: v1
        namespace: sock-shop
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: catalogue
            version: v1
        template:
          metadata:
            labels:
              app: catalogue
              version: v1
          spec:
            terminationGracePeriodSeconds: 5
            containers:
            - name: catalogue
              image: weaveworksdemos/catalogue:0.3.5
              command: ["/app"]
              args:
                - -port=80
              resources:
                limits:
                  cpu: 200m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 100Mi
              ports:
                - containerPort: 80
              securityContext:
                runAsNonRoot: true
                runAsUser: 10001
                capabilities:
                  drop:
                    - all
                  add:
                    - NET_BIND_SERVICE
                readOnlyRootFilesystem: true
              livenessProbe:
                httpGet:
                  path: /health
                  port: 80
                initialDelaySeconds: 300
                periodSeconds: 3
              readinessProbe:
                httpGet:
                  path: /health
                  port: 80
                initialDelaySeconds: 180
                periodSeconds: 3
          nodeSelector:
            beta.kubernetes.io/os: linux

- name: Create catalogue service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: catalogue
        annotations:
          prometheus.io/scrape: 'true'
        labels:
          name: catalogue
        namespace: sock-shop
      spec:
        type: ClusterIP
        ports:
          - name: http
            port: 80
            targetPort: 80
        selector:
          app: catalogue
