- name: Create orders deployment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Deployment
      metadata:
        name: orders
        labels:
          app: orders
          version: v1
        namespace: sock-shop
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: orders
            version: v1
        template:
          metadata:
            labels:
              app: orders
              version: v1
          spec:
            terminationGracePeriodSeconds: 5
            containers:
            - name: orders
              image: weaveworksdemos/orders:0.4.7
              env:
                - name: JAVA_OPTS
                  value: -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
              resources:
                limits:
                  cpu: 500m
                  memory: 500Mi
                requests:
                  cpu: 100m
                  memory: 300Mi
              ports:
              - containerPort: 80
              securityContext:
                runAsNonRoot: true
                runAsUser: 10001
                capabilities:
                  drop:
                    - all
                  add:
                    - NET_BIND_SERVICE
                readOnlyRootFilesystem: true
              volumeMounts:
                - mountPath: /tmp
                  name: tmp-volume
              livenessProbe:
                httpGet:
                  path: /health
                  port: 80
                initialDelaySeconds: 300
                periodSeconds: 3
              readinessProbe:
                httpGet:
                  path: /health
                  port: 80
                initialDelaySeconds: 30
                periodSeconds: 3
            volumes:
              - name: tmp-volume
                emptyDir:
                  medium: Memory
            nodeSelector:
              beta.kubernetes.io/os: linux

- name: Create orders service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: orders
        annotations:
          prometheus.io/scrape: 'true'
        labels:
          name: orders
        namespace: sock-shop
      spec:
        type: ClusterIP
        ports:
          - name: http
            port: 80
            targetPort: 80
        selector:
          app: orders
