- name: Create user deployment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Deployment
      metadata:
        name: user
        labels:
          app: user
          version: v1
        namespace: sock-shop
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: user
            version: v1
        template:
          metadata:
            labels:
              app: user
              version: v1
          spec:
            terminationGracePeriodSeconds: 5
            containers:
            - name: user
              image: weaveworksdemos/user:0.4.7
              resources:
                limits:
                  cpu: 300m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 100Mi
              env:
                - name: mongo
                  value: user-db:27017
              ports:
              - containerPort: 80
              securityContext:
                runAsNonRoot: true
                runAsUser: 10001
                capabilities:
                  drop:
                    - all
                  add:
                    - NET_BIND_SERVICE
                readOnlyRootFilesystem: true
              livenessProbe:
                httpGet:
                  path: /health
                  port: 80
                initialDelaySeconds: 300
                periodSeconds: 3
              readinessProbe:
                httpGet:
                  path: /health
                  port: 80
                initialDelaySeconds: 180
                periodSeconds: 3
            nodeSelector:
              beta.kubernetes.io/os: linux

- name: Create user service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: user
        annotations:
          prometheus.io/scrape: 'true'
        labels:
          name: user
        namespace: sock-shop
      spec:
        type: ClusterIP
        ports:
          - name: http
            port: 80
            targetPort: 80
        selector:
          app: user
